-- =========================================================
-- SkillSwap Database Schema (MySQL)
-- =========================================================
CREATE DATABASE IF NOT EXISTS skillswap_db;
USE skillswap_db;

-- ---------------------------------------------------------
-- USERS  (both students and admin live here; role decides)
-- ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    user_id        INT AUTO_INCREMENT PRIMARY KEY,
    reg_no         VARCHAR(30)  UNIQUE NOT NULL,
    name           VARCHAR(100) NOT NULL,
    email          VARCHAR(100) UNIQUE NOT NULL,
    password_hash  VARCHAR(256) NOT NULL,
    role           VARCHAR(20)  NOT NULL DEFAULT 'STUDENT', -- STUDENT / ADMIN
    year_of_study  INT,
    department     VARCHAR(100),
    rating_sum     INT DEFAULT 0,
    rating_count   INT DEFAULT 0,
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ---------------------------------------------------------
-- SKILLS  (master catalogue, e.g. "Java", "Guitar", "Photoshop")
-- ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS skills (
    skill_id    INT AUTO_INCREMENT PRIMARY KEY,
    skill_name  VARCHAR(100) UNIQUE NOT NULL,
    category    VARCHAR(50)
);

-- ---------------------------------------------------------
-- SKILLS A STUDENT CAN TEACH
-- ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS user_teach_skills (
    id            INT AUTO_INCREMENT PRIMARY KEY,
    user_id       INT NOT NULL,
    skill_id      INT NOT NULL,
    proficiency   VARCHAR(20) NOT NULL, -- BEGINNER / INTERMEDIATE / ADVANCED / EXPERT
    FOREIGN KEY (user_id)  REFERENCES users(user_id)  ON DELETE CASCADE,
    FOREIGN KEY (skill_id) REFERENCES skills(skill_id) ON DELETE CASCADE,
    UNIQUE (user_id, skill_id)
);

-- ---------------------------------------------------------
-- SKILLS A STUDENT WANTS TO LEARN
-- ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS user_learn_skills (
    id             INT AUTO_INCREMENT PRIMARY KEY,
    user_id        INT NOT NULL,
    skill_id       INT NOT NULL,
    desired_level  VARCHAR(20) NOT NULL,
    FOREIGN KEY (user_id)  REFERENCES users(user_id)  ON DELETE CASCADE,
    FOREIGN KEY (skill_id) REFERENCES skills(skill_id) ON DELETE CASCADE,
    UNIQUE (user_id, skill_id)
);

-- ---------------------------------------------------------
-- EXCHANGE REQUESTS
-- ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS exchange_requests (
    request_id          INT AUTO_INCREMENT PRIMARY KEY,
    sender_id            INT NOT NULL,
    receiver_id           INT NOT NULL,
    skill_requested_id   INT NOT NULL,
    skill_offered_id     INT,
    message              VARCHAR(500),
    status               VARCHAR(20) NOT NULL DEFAULT 'PENDING', -- PENDING/ACCEPTED/REJECTED/CANCELLED/COMPLETED
    created_at           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (sender_id)          REFERENCES users(user_id),
    FOREIGN KEY (receiver_id)        REFERENCES users(user_id),
    FOREIGN KEY (skill_requested_id) REFERENCES skills(skill_id),
    FOREIGN KEY (skill_offered_id)   REFERENCES skills(skill_id)
);

-- ---------------------------------------------------------
-- SESSIONS  (scheduled once a request is ACCEPTED)
-- ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS sessions (
    session_id        INT AUTO_INCREMENT PRIMARY KEY,
    request_id        INT NOT NULL,
    session_datetime   DATETIME NOT NULL,
    duration_minutes   INT DEFAULT 60,
    mode               VARCHAR(20) DEFAULT 'ONLINE',   -- ONLINE / OFFLINE
    location_or_link   VARCHAR(255),
    status             VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED', -- SCHEDULED/COMPLETED/CANCELLED
    FOREIGN KEY (request_id) REFERENCES exchange_requests(request_id)
);

-- ---------------------------------------------------------
-- FEEDBACK  (rating given after a completed session)
-- ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS feedback (
    feedback_id  INT AUTO_INCREMENT PRIMARY KEY,
    session_id   INT NOT NULL,
    rated_by     INT NOT NULL,
    rated_to     INT NOT NULL,
    rating       INT NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comments     VARCHAR(500),
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (session_id) REFERENCES sessions(session_id),
    FOREIGN KEY (rated_by)   REFERENCES users(user_id),
    FOREIGN KEY (rated_to)   REFERENCES users(user_id)
);

-- Default admin account (password = "admin123", already SHA-256 hashed)
-- Hash generated by com.skillswap.util.PasswordUtil.hash("admin123")
INSERT IGNORE INTO users (reg_no, name, email, password_hash, role, year_of_study, department)
VALUES ('ADMIN0001', 'System Admin', 'admin@srmist.edu.in',
        '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a',
        'ADMIN', NULL, 'Administration');
